# Notebook Contents
1. Importing Libraries
2. Importing Data
3. Data Wrangling Procedures
4. Data Consistency Checks
5. Exporting Cleaned Dataframe

# 1. Importing Libraries

In [35]:
#Importing Libraries
import pandas as pd
import numpy as np
import os

# 2. Importing Data

In [36]:
#Creating path
path =r'C:\Users\smflo\Documents\Gun Violence Analysis'

In [37]:
#Importing 6.1 Gun Violence Data.csv
df_guns = pd.read_csv(os.path.join(path, '02 Data','Original Data','6.1 Gun Violence Data.csv'), index_col = False)

# 3. Data Wrangling Procedures

In [38]:
#Viewing first 5 rows
df_guns.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,1/1/2013,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,1/1/2013,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,1/1/2013,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,1/5/2013,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,...,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Stacie Philbrook||1::Christopher Ratliffe||...,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,1/7/2013,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Danielle Imani Jameison||1::Maurice Eugene ...,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0

In [39]:
#Checking Shape 
df_guns.shape

(239677, 29)

## 3a. Dropping Columns

In [40]:
#Dropping columns due to not needed for analysis
df_guns= df_guns.drop(columns = ['address', 'incident_url', 'source_url', 'incident_url_fields_missing', 'participant_name', 'sources', 'notes', 'latitude', 'longitude', 'location_description'])

In [41]:
#Viewing first 5 rows
df_guns.head()

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_stolen,gun_type,incident_characteristics,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,state_house_district,state_senate_district
0,461105,1/1/2013,Pennsylvania,Mckeesport,0,4,14.0,NaN,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,NaN,NaN
1,460726,1/1/2013,California,Hawthorne,1,3,43.0,NaN,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,62.0,35.0
2,478855,1/1/2013,Ohio,Lorain,1,3,9.0,0::Unknown||1::Unknown,0::Unknown||1::Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,56.0,13.0
3,478925,1/5/2013,Colorado,Aurora,4,0,6.0,NaN,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,40.0,28.0
4,478959,1/7/2013,North Carolina,Greensboro,2,2,6.0,0::Unknown||1::Unknown,0::Handgun||1::Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,62.0,27.0

In [42]:
#Checking value counts
df_guns['gun_stolen'].value_counts(dropna = False)

0::Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    121310
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            99498
0::Unknown||1::Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          6116
0::Stolen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       4503
0::Unknown||1::Unknown||2::Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1484
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ...
0::Unknown||1::Unknown||2::Unknown||3::Unknown||4::Unknown||5::Unknown||6::Stolen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
0::Stolen||1::Unknown||2::Unknown||3::Unknown||4::Unknown||5::Unknown||6::Unknown||7::Unknown||8::Stolen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
0::Unknown||1::Unknown||2::Unknown||3::Unknown||4::Unknown||5::Unknown||6::Unknown||7::Unknown||8::Unknown||9::Unknown||10::Unknown||11::Unknown||12::Unknown||13::Unknown||14::Unknown||15::Unknown||16::Unknown||17::Unknown||18::Unknown||19::Unknown||20::Unknown||21::Unknown||22::Unknown||23::Unknown||24::Unknown||25::Unknown||26::Unknown||27::Unknown||28::Unknown||29::Unknown||30::Unknown||31::Unknown||32::Unknown||33::Unknown||34::Unknown||35::Unknown||36::Unknown||37::Unknown||38::Unknown||39::Unknown||40::Unknown||41::Unknown||42::Unknown||43::Unknown||44::Unknown||45::Unknown||46::Unknown||47::Unknown||48::Unknown||49::Unknown||50::Unknown||51::Unknown||52::Unknown||53::Unknown||54::Unknown||55::Unknown||56::Unknown||57::Unknown||58::Unknown||59::Unknown||60::Unknown||61::Unknown||62::Unknown||63::Unknown||64::Unknown||65::Unknown||66::Unknown||67::Unknown||68::Unknown||69::Unknown||70::Unknown||71::Unknown||72::Unknown||73::Unknown||74::Unknown||75::Unknown||76::Unknown||77::Unknown||78::Unknown||79::Unknown||80::Unknown||81::Unknown||82::Unknown||83::Unknown||84::Unknown||85::Unknown||86::Unknown||87::Unknown||88::Unknown||89::Unknown||90::Unknown||91::Unknown||92::Unknown||93::Unknown||94::Unknown||95::Unknown||96::Unknown||97::Unknown||98::Unknown||99::Unknown||100::Unknown||101::Unknown||102::Unknown||103::Unknown||104::Unknown||105::Unknown||106::Unknown||107::Unknown||108::Unknown||109::Unknown||110::Unknown||111::Unknown||112::Unknown||113::Unknown||114::Unknown         1
0::Not-stolen||1::Not-stolen||2::Not-stolen||3::Not-stolen||4::Not-stolen||5::Not-stolen||6::Not-stolen||7::Not-stolen||8::Not-stolen||9::Not-stolen||10::Not-stolen||11::Not-stolen||12::Not-stolen||13::Not-stolen||14::Not-stolen||15::Not-stolen||16::Not-stolen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
0::Stolen||1::Unknown||2::Unknown||3::Unknown||4::Unknown||5::Unknown||6::Unknown||7::Unknown||8::Unknown||9::Unknown||10::Unknown||11::Unknown||12::Unknown||13::Unknown||14::Unknown||15::Unknown||16::Unknown||17::Unknown||18::Unknown||19::Unknown||20::Unknown||21::Unknown||22::Unknown||23::Unknown||24::Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Name: gun_stolen, Length: 350, dtype: int64

In [43]:
#Checking value counts 
df_guns['gun_type'].value_counts(dropna = False)

NaN                                                                                                                                                                                                                 99451
0::Unknown                                                                                                                                                                                                          93559
0::Handgun                                                                                                                                                                                                          13018
0::9mm                                                                                                                                                                                                               4599
0::Unknown||1::Unknown                                                                                                                                                                                               2410
                                                                                                                                                                                                                    ...
0::357 Mag||1::38 Spl||2::22 LR                                                                                                                                                                                         1
0::223 Rem [AR-15]||1::22 LR||2::22 LR||3::Handgun||4::Handgun||5::Handgun||6::Handgun                                                                                                                                  1
0::223 Rem [AR-15]||1::Shotgun||2::Shotgun||3::Shotgun||4::Rifle||5::Rifle||6::Rifle||7::Rifle||8::Rifle||9::Rifle||10::Handgun||11::Handgun||12::Handgun||13::Handgun                                                  1
0::Other||1::Rifle||2::Rifle||3::Shotgun||4::Shotgun||5::Shotgun||6::Shotgun||7::Shotgun||8::Handgun||9::Handgun||10::Handgun||11::Handgun||12::Handgun||13::Handgun||14::Handgun||15::Handgun||16::7.62 [AK-47]        1
0::357 Mag||1::44 Mag||2::45 Auto||3::Rifle||4::Rifle||5::Rifle||6::Rifle||7::Rifle                                                                                                                                     1
Name: gun_type, Length: 2503, dtype: int64

In [44]:
#Checking value counts
df_guns['n_guns_involved'].value_counts(dropna = False)

1.0      127548
NaN       99451
2.0        7477
3.0        2021
4.0         871
          ...
158.0         1
189.0         1
85.0          1
96.0          1
127.0         1
Name: n_guns_involved, Length: 107, dtype: int64

In [45]:
#Checking value counts
df_guns['participant_relationship'].value_counts(dropna = False)

NaN                                                                                                                                                                                                                                                                                                                                                                               223903
1::Significant others - current or former                                                                                                                                                                                                                                                                                                                                           2651
1::Family                                                                                                                                                                                                                                                                                                                                                                           2573
1::Armed Robbery                                                                                                                                                                                                                                                                                                                                                                    1874
1::Armed Robbery||2::Armed Robbery                                                                                                                                                                                                                                                                                                                                                  1100
                                                                                                                                                                                                                                                                                                                                                                                   ...
2::Home Invasion - Perp Does Not Know Victim||3::Home Invasion - Perp Does Not Know Victim||4::Home Invasion - Perp Does Not Know Victim||5::Gang vs Gang                                                                                                                                                                                                                              1
4::Drive by - Random victims||5::Drive by - Random victims||6::Drive by - Random victims                                                                                                                                                                                                                                                                                               1
7::Aquaintance                                                                                                                                                                                                                                                                                                                                                                         1
4::Mass shooting - Random victims||5::Mass shooting - Random victims                                                                                                                                                                                                                                                                                                                   1
1::Home Invasion - Perp Does Not Know Victim||2::Home Invasion - Perp Does Not Know Victim||3::Home Invasion - Perp Does Not Know Victim||4::Home Invasion - Perp Does Not Know Victim||5::Home Invasion - Perp Does Not Know Victim||6::Home Invasion - Perp Does Not Know Victim||7::Home Invasion - Perp Does Not Know Victim||8::Home Invasion - Perp Does Not Know Victim         1
Name: participant_relationship, Length: 285, dtype: int64

In [46]:
#Dropping columns due to too many missing values
df_guns= df_guns.drop(columns = ['gun_stolen', 'participant_relationship'])

In [47]:
#Viewing first 5 rows
df_guns.head()

,incident_id,date,state,city_or_county,n_killed,n_injured,congressional_district,gun_type,incident_characteristics,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_status,participant_type,state_house_district,state_senate_district
0,461105,1/1/2013,Pennsylvania,Mckeesport,0,4,14.0,NaN,Shot - Wounded/Injured||Mass Shooting (4+ vict...,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,NaN,NaN
1,460726,1/1/2013,California,Hawthorne,1,3,43.0,NaN,"Shot - Wounded/Injured||Shot - Dead (murder, a...",NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,62.0,35.0
2,478855,1/1/2013,Ohio,Lorain,1,3,9.0,0::Unknown||1::Unknown,"Shot - Wounded/Injured||Shot - Dead (murder, a...",2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,56.0,13.0
3,478925,1/5/2013,Colorado,Aurora,4,0,6.0,NaN,"Shot - Dead (murder, accidental, suicide)||Off...",NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,40.0,28.0
4,478959,1/7/2013,North Carolina,Greensboro,2,2,6.0,0::Handgun||1::Handgun,"Shot - Wounded/Injured||Shot - Dead (murder, a...",2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,62.0,27.0

## 3b. Checking/Changing Data Types

In [48]:
#Checking descriptive statistics
df_guns.describe()

,incident_id,n_killed,n_injured,congressional_district,n_guns_involved,state_house_district,state_senate_district
count,2.396770e+05,239677.000000,239677.000000,227733.000000,140226.000000,200905.000000,207342.00000
mean,5.593343e+05,0.252290,0.494007,8.001265,1.372442,55.447132,20.47711
std,2.931287e+05,0.521779,0.729952,8.480835,4.678202,42.048117,14.20456
min,9.211400e+04,0.000000,0.000000,0.000000,1.000000,1.000000,1.00000
25%,3.085450e+05,0.000000,0.000000,2.000000,1.000000,21.000000,9.00000
50%,5.435870e+05,0.000000,0.000000,5.000000,1.000000,47.000000,19.00000
75%,8.172280e+05,0.000000,1.000000,10.000000,1.000000,84.000000,30.00000
max,1.083472e+06,50.000000,53.000000,53.000000,400.000000,901.000000,94.00000

In [49]:
#Changing data type
df_guns['incident_id'] = df_guns['incident_id'].astype('str')

In [50]:
#Changing data type
df_guns['congressional_district'] = df_guns['congressional_district'].astype('str')

In [51]:
#Changing data type
df_guns['state_house_district'] = df_guns['state_house_district'].astype('str')

In [52]:
#Changing data type
df_guns['state_senate_district'] = df_guns['state_senate_district'].astype('str')

In [53]:
#Checking descriptive statistics
df_guns.describe()

            n_killed      n_injured  n_guns_involved
count  239677.000000  239677.000000    140226.000000
mean        0.252290       0.494007         1.372442
std         0.521779       0.729952         4.678202
min         0.000000       0.000000         1.000000
25%         0.000000       0.000000         1.000000
50%         0.000000       0.000000         1.000000
75%         0.000000       1.000000         1.000000
max        50.000000      53.000000       400.000000

# 4. Data Consistency Checks

## 4a. Mixed Data Types

In [54]:
#Checking for mixed data types
for col in df_guns.columns.tolist():
  weird = (df_guns[[col]].applymap(type) != df_guns[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_guns[weird]) > 0:
    print (col)

gun_type
incident_characteristics
participant_age
participant_age_group
participant_gender
participant_status
participant_type

In [55]:
#Changing data type
df_guns['gun_type'] = df_guns['gun_type'].astype('str')

In [56]:
#Changing data type
df_guns['incident_characteristics'] = df_guns['incident_characteristics'].astype('str')

In [57]:
#Changing data type
df_guns['participant_age'] = df_guns['participant_age'].astype('str')

In [58]:
#Changing data type
df_guns['participant_age_group'] = df_guns['participant_age_group'].astype('str')

In [59]:
#Changing data type
df_guns['participant_gender'] = df_guns['participant_gender'].astype('str')

In [60]:
#Changing data type
df_guns['participant_status'] = df_guns['participant_status'].astype('str')

In [61]:
#Changing data type
df_guns['participant_type'] = df_guns['participant_type'].astype('str')

## 4b. Missing Values

In [62]:
#Checking for missing values
df_guns.isnull().sum()

incident_id                     0
date                            0
state                           0
city_or_county                  0
n_killed                        0
n_injured                       0
congressional_district          0
gun_type                        0
incident_characteristics        0
n_guns_involved             99451
participant_age                 0
participant_age_group           0
participant_gender              0
participant_status              0
participant_type                0
state_house_district            0
state_senate_district           0
dtype: int64

In [63]:
#Checking median
df_guns.median()

C:\Users\smflo\AppData\Local\Temp\ipykernel_2920\562998084.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_guns.median()

incident_id               543587.0
n_killed                       0.0
n_injured                      0.0
congressional_district         5.0
n_guns_involved                1.0
state_house_district          47.0
state_senate_district         19.0
dtype: float64

In [64]:
#Imputing missing values with median
df_guns['n_guns_involved']= df_guns['n_guns_involved'].fillna(df_guns['n_guns_involved'].median())

In [65]:
#Checking for missing values
df_guns.isnull().sum()

incident_id                 0
date                        0
state                       0
city_or_county              0
n_killed                    0
n_injured                   0
congressional_district      0
gun_type                    0
incident_characteristics    0
n_guns_involved             0
participant_age             0
participant_age_group       0
participant_gender          0
participant_status          0
participant_type            0
state_house_district        0
state_senate_district       0
dtype: int64

## 4c. Duplicates

In [66]:
#Creating hecking for duplicates
df_dups = df_guns[df_guns.duplicated()]

In [67]:
#Viewing df_dups
df_dups

Empty DataFrame
Columns: [incident_id, date, state, city_or_county, n_killed, n_injured, congressional_district, gun_type, incident_characteristics, n_guns_involved, participant_age, participant_age_group, participant_gender, participant_status, participant_type, state_house_district, state_senate_district]
Index: []

No duplicates found

In [68]:
#Checking shape of cleaned dataframe
df_guns.shape

(239677, 17)

# 5. Exporting Cleaned Dataframe

In [69]:
#Exporting updated dataframe
df_guns.to_csv(os.path.join(path, '02 Data','Prepared Data', 'guns_clean.csv'))